#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FluidsynthMidiServices.Resource", IsApplication=true)]

namespace FluidsynthMidiServices
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int Icon = 2130771968;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int editText = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int mainSurface = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int openFreeStylePad = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int playChord = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int playMML = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int playSong = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int programSelector = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int songFileNameOrUrlEditText = 2130837511;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int RhythmPad = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int hello = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F050000
			public const int device_info = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
